In [1]:
# import opencv module
import cv2
from matplotlib import pyplot as plt
import numpy as np
import copy

# For interactive python:
%matplotlib inline  

In [2]:
# termination criteria
criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.01)
# prepare object points, like (0,0,0), (1,0,0), (2,0,0) ....,(6,5,0)

objp = np.zeros((7*7,3), np.float32)
objp[:,:2] = np.mgrid[0:7,0:7].T.reshape(-1,2)

# Arrays to store object points and image points from all the images.
objpoints = [] # 3d point in real world space
imgpoints = [] # 2d points in image plane.

In [3]:
cap = cv2.VideoCapture('newinput.avi')
fourcc = cv2.VideoWriter_fourcc(*'XVID')
frame_width = int( cap.get(cv2.CAP_PROP_FRAME_WIDTH))
frame_height =int( cap.get( cv2.CAP_PROP_FRAME_HEIGHT)) 

out = cv2.VideoWriter('newoutput.avi', fourcc, 30.0,(frame_width,frame_height))

In [4]:
while True:
    success,frame = cap.read()
    if success:     
        gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        ret,corners = cv2.findChessboardCorners(gray, (7,7), None)
        
        if ret:
            objpoints.append(objp)
            corners2 = cv2.cornerSubPix(gray,corners, (11,11), (-1,-1), criteria)
            cv2.drawChessboardCorners(frame, (7,7), corners, ret)
            imgpoints.append(corners2)
        
        cv2.namedWindow('original', cv2.WINDOW_NORMAL)        
        cv2.imshow('original', frame)
        out.write(frame)
        c=cv2.waitKey(1)
        if c == 27:
            break
#         if cv2.waitKey(1) & 0xFF == ord('q'):
#             break
    else:
        break

cap.release()
out.release()
cv2.destroyAllWindows()

In [5]:
cam=cv2.VideoCapture('./newoutput.avi')
while True:
    ret, shot = cam.read()
    cv2.imshow('shot', shot)
    c=cv2.waitKey(1)
    if c == 27:
        break

cam.release()
cv2.destroyAllWindows()

error: /home/jwlee2218/opencv/opencv-3.4.0/modules/highgui/src/window.cpp:339: error: (-215) size.width>0 && size.height>0 in function imshow


In [13]:
ret

False

In [ ]:
# ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(objpoints, imgpoints, gray.shape[::-1], None, None)
# np.savez('calib.npz', mtx=mtx, dist=dist, rvecs=rvecs, tvecs=tvecs)

In [25]:
len(objpoints)

435

In [26]:
len(imgpoints)

435

In [27]:
len(corners2)

49

In [57]:
print(corners2)

[[[200.76622 177.93155]]

 [[231.78857 179.50208]]

 [[262.83783 180.93816]]

 [[293.38147 182.46268]]

 [[323.6898  183.82178]]

 [[353.67828 185.31056]]

 [[383.43262 186.59204]]

 [[199.55975 207.79657]]

 [[230.93356 209.1871 ]]

 [[262.253   210.59154]]

 [[292.95267 211.79764]]

 [[323.46426 213.18767]]

 [[353.66144 214.42328]]

 [[383.6694  215.68103]]

 [[198.35478 238.17856]]

 [[230.09535 239.41185]]

 [[261.41425 240.50931]]

 [[292.50253 241.71678]]

 [[323.2798  242.8598 ]]

 [[353.71426 244.0084 ]]

 [[383.93552 245.12862]]

 [[197.14542 269.0491 ]]

 [[229.1352  270.04022]]

 [[260.71268 271.0745 ]]

 [[292.06125 272.06552]]

 [[323.0916  273.15375]]

 [[353.7571  274.12216]]

 [[384.25925 275.1342 ]]

 [[195.80432 300.33057]]

 [[228.13031 301.27335]]

 [[260.02725 302.07587]]

 [[291.60367 302.9861 ]]

 [[322.85825 303.86023]]

 [[353.8327  304.68472]]

 [[384.64148 305.55484]]

 [[194.51033 332.32974]]

 [[227.11475 332.90192]]

 [[259.3435  333.70337]]

 [[291.2026 