In [30]:
import numpy as np
import cv2
from matplotlib import pyplot as plt

In [31]:
img= cv2.imread('test 01.tif')

In [35]:
cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [33]:
canny = cv2.Canny(img,30,70)

In [142]:
canny

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [141]:
cv2.imshow('image',canny)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [148]:
imgray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
ret,thresh = cv2.threshold(imgray,127,255,0)
im2, contours, hierarchy = cv2.findContours(thresh,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)

In [150]:
cv2.imshow('image',imgray)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [39]:
print(imgray.shape)
width = imgray.shape[1]
height = imgray.shape[0]
print(width)
print(height)

(720, 1280)
1280
720


In [140]:
c = max(contours, key=cv2.contourArea) #max contour
f = open('path.svg', 'w+')
f.write('<?xml version="1.0" encoding="utf-8"?>')
f.write('<svg version="1.0" id="Layer_1" width="'+str(width)+'" height="'+str(height)+'" xmlns="http://www.w3.org/2000/svg" xml:space="preserve">')
f.write('<path class="st0" d="')

for i in range(len(contours)):
#     print(c[i][0])
#     x, y = c[i][0]
#     print(x)
    f.write('M')
    for j in range(len(contours[i])):
        x,y = contours[i][j][0]
        print(x,y)
        f.write(str(x)+  ' ' + str(y)+' ')

f.write('"/>')
f.write('</svg>')
f.close()

217 407
215 409
215 502
217 504
581 504
582 503
582 497
583 496
583 495
582 494
582 489
583 488
583 487
582 486
582 481
583 480
583 479
582 478
582 472
583 471
583 470
582 469
582 466
583 465
583 464
582 463
582 458
583 457
581 455
264 455
263 454
263 450
264 449
264 448
263 447
263 441
264 440
264 439
263 438
263 433
264 432
264 431
263 430
263 424
264 423
264 422
263 421
263 416
264 415
264 414
263 413
263 408
262 407
217 407
262 407
263 408
263 413
264 414
264 415
263 416
263 421
264 422
264 423
263 424
263 430
264 431
264 432
263 433
263 438
264 439
264 440
263 441
263 447
264 448
264 449
263 450
263 454
264 455
581 455
583 457
582 458
582 463
583 464
583 465
582 466
582 469
583 470
583 471
582 472
582 478
583 479
583 480
582 481
582 486
583 487
583 488
582 489
582 494
583 495
583 496
582 497
582 503
581 504
217 504
215 502
215 409
896 383
895 384
890 384
889 385
884 385
883 386
881 386
880 387
877 387
876 388
873 388
872 389
871 389
870 390
868 390
867 391
865 391
864 392
863 392


897 236
896 236
893 239
892 239
890 241
890 243
893 246
894 246
896 248
897 248
900 251
901 251
903 253
904 253
906 255
907 255
910 258
911 258
913 260
914 260
915 261
914 262
914 263
913 264
913 265
912 266
912 267
911 268
911 269
910 270
910 271
909 272
909 274
908 275
908 276
907 277
907 278
906 279
906 280
905 281
905 282
904 283
904 284
903 285
903 288
902 289
903 290
906 290
907 291
917 291
918 292
928 292
918 292
917 291
918 290
929 290
930 291
934 291
936 293
936 303
935 304
934 303
934 294
933 293
930 293
933 293
934 294
934 303
935 304
935 314
936 315
936 322
936 315
937 314
938 315
938 322
939 322
940 323
939 324
937 324
940 324
941 323
942 323
943 322
944 322
945 321
946 321
947 320
948 320
949 319
951 319
952 318
953 318
954 317
955 317
956 316
957 316
958 315
959 315
960 314
961 314
962 313
964 313
965 312
966 312
967 313
967 314
970 317
970 318
972 320
972 321
974 323
974 324
977 327
977 328
979 330
979 331
982 334
982 335
983 336
986 336
988 334
988 333
990 331
990 330


1017 315
1015 315
1014 314
1013 314
1012 313
1011 313
1010 312
1009 312
1008 311
1007 311
1006 310
1002 310
999 313
999 314
997 316
997 317
995 319
995 320
992 323
992 324
990 326
990 327
987 330
987 331
985 333
984 333
982 331
982 330
980 328
980 327
977 324
977 323
975 321
975 320
973 318
973 317
970 314
970 313
968 311
968 310
963 310
962 311
961 311
960 312
959 312
958 313
957 313
956 314
955 314
954 315
953 315
952 316
950 316
949 317
948 317
947 318
946 318
945 319
944 319
943 320
942 320
941 321
940 321
939 322
938 321
938 315
937 314
937 304
936 303
936 293
935 292
935 291
930 291
929 290
918 290
917 289
907 289
905 287
905 286
906 285
906 284
907 283
907 282
908 281
908 280
909 279
909 278
910 277
910 276
911 275
911 274
912 273
912 271
913 270
913 269
914 268
914 267
915 266
915 265
916 264
916 263
917 262
917 261
916 260
916 259
914 257
913 257
911 255
910 255
907 252
906 252
904 250
903 250
901 248
900 248
897 245
896 245
894 243
893 243
892 242
893 241
894 241
896 239
897 

In [134]:
c = max(contours, key=cv2.contourArea) #max contour
f = open('path2.svg', 'w+')
f.write('<?xml version="1.0" encoding="utf-8"?>')
f.write('<svg version="1.0" id="Layer_1" width="'+str(width)+'" height="'+str(height)+'" xmlns="http://www.w3.org/2000/svg" xml:space="preserve">')
f.write('<path d="M')

for i in range(len(c)):
#     print(c[i][0])
    x, y = c[i][0]
    print(x,y)
    
#     for j in range(len(contours[i])):
#         x,y = contours[i][j][0]
#        print(x,y)
    f.write(str(x)+  ' ' + str(y)+' ')

f.write('"/>')
f.write('</svg>')
f.close()

214 71
213 72
208 72
207 73
202 73
201 74
198 74
197 75
194 75
193 76
191 76
190 77
188 77
187 78
185 78
184 79
182 79
181 80
180 80
179 81
177 81
176 82
175 82
174 83
173 83
172 84
171 84
170 85
169 85
168 86
167 86
166 87
165 87
163 89
162 89
161 90
160 90
158 92
157 92
154 95
153 95
150 98
149 98
142 105
141 105
136 110
136 111
130 117
130 118
127 121
127 122
124 125
124 126
122 128
122 129
121 130
121 131
119 133
119 134
118 135
118 136
117 137
117 138
116 139
116 140
115 141
115 142
114 143
114 145
113 146
113 147
112 148
112 149
111 150
111 152
110 153
110 155
109 156
109 157
108 158
108 161
107 162
107 165
106 166
106 169
105 170
105 174
104 175
104 181
103 182
103 210
104 211
104 217
105 218
105 223
106 224
106 226
107 227
107 230
108 231
108 234
109 235
109 237
110 238
110 239
111 240
111 242
112 243
112 245
113 246
113 247
114 248
114 249
115 250
115 251
116 252
116 253
117 254
117 256
119 258
119 259
120 260
120 261
122 263
122 264
124 266
124 267
126 269
126 270
129 273
129

In [133]:
len(c)

344

In [114]:
image = cv2.drawContours(img, contours, -1, (0,255,0), 3)

In [122]:
contours

[array([[[217, 407]],
 
        [[215, 409]],
 
        [[215, 502]],
 
        [[217, 504]],
 
        [[581, 504]],
 
        [[582, 503]],
 
        [[582, 497]],
 
        [[583, 496]],
 
        [[583, 495]],
 
        [[582, 494]],
 
        [[582, 489]],
 
        [[583, 488]],
 
        [[583, 487]],
 
        [[582, 486]],
 
        [[582, 481]],
 
        [[583, 480]],
 
        [[583, 479]],
 
        [[582, 478]],
 
        [[582, 472]],
 
        [[583, 471]],
 
        [[583, 470]],
 
        [[582, 469]],
 
        [[582, 466]],
 
        [[583, 465]],
 
        [[583, 464]],
 
        [[582, 463]],
 
        [[582, 458]],
 
        [[583, 457]],
 
        [[581, 455]],
 
        [[264, 455]],
 
        [[263, 454]],
 
        [[263, 450]],
 
        [[264, 449]],
 
        [[264, 448]],
 
        [[263, 447]],
 
        [[263, 441]],
 
        [[264, 440]],
 
        [[264, 439]],
 
        [[263, 438]],
 
        [[263, 433]],
 
        [[264, 432]],
 
        [[264, 4

In [115]:
cv2.imshow('image', image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [110]:
len(c[1])

1

In [111]:
c[0]

array([[214,  71]], dtype=int32)

In [61]:
len(contours)

93

In [82]:
len(contours[90])

336

In [101]:
contours[2][0][0]

array([896, 383], dtype=int32)

In [118]:
t=0

In [119]:
for i in range(len(contours)):
#     print(c[i][0])
#     x, y = c[i][0]
#     print(x)
    for j in range(len(contours[i])):
        x,y = contours[i][j][0]
        t=t+1

In [120]:
t

3585